### ISSUE TITLE
Search in volunteer Dashboard not working

### ISSUE THREAD

**Issue by ManasaG124** [Rounaknayee/frontend#4]
The search functionality is currently broken for the volunteer portal under Jobs section.

### Steps to reproduce
1. Login as a `volunteer`
2. Navigate to the `jobs` section in the menu sidebar.
3. Click on the search filter box and hit a single backspace (or you can type anything in the box)
4. The screen becomes completely blank

### System and Browser Information
1. Operating System: Windows 11 22H2 (10.0.22621.963)
2. Browser: Google Chrome (110.0.5464.0)

### Possible Solution
The hook handling search is currently receiving incorrect parameters visible from the DevTools screenshot attached below. Fixing this method should fix the issue.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/120154798/208958895-a4482961-8f28-4c06-911e-8c80506b6434.png">

**Comment by Rounaknayee** [comment]
fixed with commit [03a47c8](https://github.com/Rounaknayee/volunteer-connect/commit/03a47c8495873c5d11e4caa3b03ef2e93129172f)
